#ifndef WIFI_MOCK_TYPE_H
#define WIFI_MOCK_TYPE_H

typedef enum {
    MOCK_WL_NO_SHIELD = 255,
    MOCK_WL_NO_MODULE = MOCK_WL_NO_SHIELD,
    MOCK_WL_IDLE_STATUS = 0,
    MOCK_WL_CONNECTED = 3,
    MOCK_WL_CONNECTED_FAILED,
    MOCK_WL_CONNECTION_LOST,
    MOCK_WL_DISCONNECTED,
} wl_mock_status_t;

#endif
