name: IoT Chas Advance CI Pipeline
on:
    push:
        branches:
            - main
            - develop
            - feature-**
            - fix-**
    pull_request:
        branches:
            - main
            - develop

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Setup Python
              if: ${{ !env.ACT }} # skip when testing locally with act
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit hooks (formatting and linting)
              run: pre-commit run --all-files || true

            - name: Commit changes from pre-commit formatting (if any)
              if: ${{ !env.ACT }}
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                  commit_message: 'CI pre-commit: Auto-formatting and linting'
                  branch: ${{ github.head_ref || github.ref_name }}

    check-build-firmware:
        needs: [pre-commit]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                board: [uno_r4_wifi_ci, esp32_broker_ci]
                include:
                    - board: uno_r4_wifi_ci
                      folder: Arduino
                      artifact_name: sensor-package-firmware
                    - board: esp32_broker_ci
                      folder: S3
                      artifact_name: esp32-s3-broker-firmware
        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Setup python
              if: ${{ !env.ACT }} # skip when testing locally with act
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install PlatformIO Core
              run: pip install platformio

            - name: Load secrets
              run: |
                  if [ -n "${ACT:-}" ]; then
                    echo "Running with act, loading from .env"
                    export $(grep -v '^#' .env | xargs)
                  else
                    echo "Running on GitHub Actions, loading from GitHub Secrets"
                    export SECRET_SSID=${{secrets.SECRET_SSID}}
                    export SECRET_PASSWORD=${{secrets.SECRET_PASSWORD}}
                    export SERVER_IP1=${{secrets.SERVER_IP1}}
                    export SERVER_IP2=${{secrets.SERVER_IP2}}
                    export SERVER_IP3=${{secrets.SERVER_IP3}}
                    export SERVER_IP4=${{secrets.SERVER_IP4}}
                    export SERVER_PORT=${{secrets.SERVER_PORT}}
                  fi
                  mkdir -p ${{matrix.folder}}/include
                  cat > ${{matrix.folder}}/include/secrets.h <<EOL
                  #ifndef SECRETS_H
                  #define SECRETS_H

                  #define SECRET_SSID "${SECRET_SSID}"
                  #define SECRET_PASSWORD "${SECRET_PASSWORD}"
                  #define SERVER_IP1 "${SERVER_IP1}"
                  #define SERVER_IP2 "${SERVER_IP2}"
                  #define SERVER_IP3 "${SERVER_IP3}"
                  #define SERVER_IP4 "${SERVER_IP4}"
                  #define SERVER_PORT "${SERVER_PORT}"

                  #endif
                  EOL

            - name: Run PlatformIO check (Static Analysis) ${{matrix.board}}
              run: cd ${{matrix.folder}} && pio check -e ${{matrix.board}}

            - name: Build firmware (${{matrix.board}})
              run: cd ${{matrix.folder}} && pio run -e ${{matrix.board}}

            - name: Upload compiled firmware (.bin)
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.artifact_name }}
                  path: ${{ matrix.folder }}/.pio/build/${{ matrix.board }}/*.bin
                  if-no-files-found: error
                  retention-days: 1

    docker-build:
        runs-on: ubuntu-latest
        needs: [check-build-firmware]
        steps:
            - uses: actions/checkout@v5

            - name: Build Docker image
              run: docker build -t iot-chas-advance:ci -t iot-chas-advance:${{ github.sha }} .

            - name: Save and upload image artifact
              run: |
                  if [ -n "${ACT:-}" ]; then
                    echo "Running locally with act: no gzip"
                    docker save iot-chas-advance:ci -o image.tar
                  else
                    echo "Running on Github Actions: saving image with gzip"
                    docker save iot-chas-advance:ci | gzip > image.tar.gz
                  fi

            - name: Upload image artifact
              if: ${{!env.ACT}}
              uses: actions/upload-artifact@v4
              with:
                  name: iot-docker-image
                  path: image.tar.gz
                  if-no-files-found: error
                  retention-days: 1
